#! /bin/sh

PREREQ=""
DESCRIPTION="Setting hostname..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

echo "$HOST" > /root/etc/hostname
cat > /root/etc/hosts <<EOF
127.0.0.1 localhost
127.0.1.1 ${HOST}.liquid.glx ${HOST}
# send these domains through squid
127.0.1.2    www.endpoint.com kh.google.com khmdb.google.com mw1.google.com mw2.google.com cbk0.google.com

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

10.42.42.1    lg1
10.42.42.2    lg2
10.42.42.3    lg3
10.42.42.4    lg4
10.42.42.5    lg5
10.42.42.6    lg6
10.42.42.7    lg7
10.42.42.8    lg8

EOF
cat > /root/etc/hosts.squid <<EOF
127.0.0.1 localhost
127.0.1.1 ${HOST}.liquid.glx ${HOST}

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

10.42.42.1    lg1
10.42.42.2    lg2
10.42.42.3    lg3
10.42.42.4    lg4
10.42.42.5    lg5
10.42.42.6    lg6
10.42.42.7    lg7
10.42.42.8    lg8

EOF
hostname "$HOST"

log_end_msg
